### ISSUE TITLE
no good  way to make optional dynamic segments

### ISSUE THREAD

**Issue by mgenev** [tildeio/router.js#102]
The whole Ember app breaks if a dynamic segment is defined, but not provided. It gives a strange non-descriptive error. There is no good way to make parameters optional. 

People suggested nesting routes which makes the route available, but then it makes a whole lot more complications with which template, model and controller are loaded.

This is a really fundamental feature and the implementation is a huge pain in the ass, I've wasted hours and still haven't made it work and while in something like Express params are optional and it just works.

**Comment by nathanhammond** [comment]
Closing in favor of https://github.com/emberjs/rfcs/pull/154
