### ISSUE TITLE
Provide API to extend HandlerInfo implementations

### ISSUE THREAD

**Issue by ppcano** [tildeio/router.js#103]
`HandlerInfo` defines a `resolve` method to provide hooks that when returning a promise, it needs to be resolved to complete a route transition.

The API hooks (`beforeModel`, `model`, `afterModel`) are well documented at EmberJS. The route transition can be aborted based on the promise hook result and ensure that the transition cannot be completed if any hook promise has not been fulfilled.

``` js
    return Promise.resolve(undefined, this.promiseLabel("Start handler"))
           .then(checkForAbort, null, this.promiseLabel("Check for abort"))
           .then(beforeModel, null, this.promiseLabel("Before model"))
           .then(checkForAbort, null, this.promiseLabel("Check if aborted during 'beforeModel' hook"))
           .then(model, null, this.promiseLabel("Model"))
           .then(checkForAbort, null, this.promiseLabel("Check if aborted in 'model' hook"))
           .then(afterModel, null, this.promiseLabel("After model"))
           .then(checkForAbort, null, this.promiseLabel("Check if aborted in 'afterModel' hook"))
           .then(becomeResolved, null, this.promiseLabel("Become resolved"));
```

Perhaps, I am at the wrong direction but I have missed to have a public API to extend the current behaviour to add some specific hooks. I have discussed my specific case at [Ember Animation Support](http://discuss.emberjs.com/t/animation-support-in-ember-1-1/1977/55).

**Comment by sandstrom** [comment]
I'm doing some issues-gardening 🍀 🌷  and stumbled upon this. Is this still an issue? if not, perhaps it can be closed?

**Comment by rwjblue** [comment]
I think this feature request would need to go through the emberjs/rfcs process.  I'm not super 👍  or 👎, but it does need through thought and RFC's have proven to be a great way to do that.

I'm going to close this in favor of a potential future RFC.
