### ISSUE TITLE
Bower support

### ISSUE THREAD

**Issue by DavidRouyer** [tildeio/router.js#106]
Is it possible to add tags and create a bower.json file in your project ? (You will also need to register your package on http://bower.io/)

**Comment by awebdev** [comment]
Another vote in favor of this

**Comment by donbobka** [comment]
:+1:

**Comment by nmabhinandan** [comment]
:+1:

**Comment by jshthornton** [comment]
+1

**Comment by edobry** [comment]
:+1:

**Comment by jmeas** [comment]
ping @stefanpenner @machty. Anything I can do to help land this? route-recognizer is set up with Bower...it's kinda weird that this lib doesn't!

**Comment by coquin** [comment]
+1

**Comment by nathanhammond** [comment]
router.js has been imported into Ember via Bower for a long time, we simply didn't publish it and instead addressed it via hash. We just added support for router.js with npm as `router_js`. Bower support should be considered deprecated.

The Ember community is moving away from Bower as a tool and we don't intend to continue supporting it forever. If you'd like to discuss that further please stop by the [Ember Community Slack](https://ember-community-slackin.herokuapp.com/)!
