### ISSUE TITLE
IE8 default keyword use in route-recognizer and rsvp AMD definition

### ISSUE THREAD

**Issue by TheFuzzball** [tildeio/router.js#107]
IE8 will throw an error when a name or key is equal to a JavaScript reserved word.
The distribution file for router.js defines:

```
define("route-recognizer", [], function() { return {default: RouteRecognizer}; });
```

and:

```
define("rsvp/promise", [], function() { return {default: RSVP.Promise}; });
```

Both of these definitions will error in IE8 due to the unquoted `default` usage.

I don't know if you support IE8, but router.js appears to run fine if you simply quote the reserved word keys:

```
define("route-recognizer", [], function() { return {"default": RouteRecognizer}; });
define("rsvp/promise", [], function() { return {"default": RSVP.Promise}; });
```

Just letting you know.

**Comment by rwjblue** [comment]
We have dropped support for IE8 at this point, so I am going to close...
