### ISSUE TITLE
updateUrl hook gets undefined segments.

### ISSUE THREAD

**Issue by TheFuzzball** [tildeio/router.js#111]
I'm using router.js standalone and I'm performing a transition from one gallery item to another. My setup:

```
match("/:ajaxSection).to("fetchSection, function(match) {
    match("/").to("hideMenu")
    match("/gallery").to("showGallery", function(match) {
        match("/:index").to("showGalleryItem")
    })
})
```

So, a URL like: /main/gallery/6 would open the page with the gallery on item 6, which is fine.

But when (from in the gallery module) I do:

```
router.transitionTo("showGalleryItem", {index:7})
```

the gallery module gets the proper model and everything works, except that my updateUrl method gets a URL that looks like _"/undefined/gallery/undefined"_.

After poking around in router.js I can see that it matches URL components to an object, and looking at the router.state.params, it appears to have the proper data, but it's not being used.

Am I doing something stupid or is this a bug?

**Comment by nathanhammond** [comment]
@TheFuzzball Sorry to leave this open for so long without addressing it. It's highly unlikely that this remains an issue over two years later with no additional corroborating reports. If you're able to reproduce the failing scenario in a current version of router.js we'd be glad to revisit and investigate!
