### ISSUE TITLE
package.json - no dependencies for rsvp and route-recognizer

### ISSUE THREAD

**Issue by ghost23** [tildeio/router.js#137]
Hi,

I just noted, that there are no dependencies in the package.json, only devDependencies. But rsvp and route-recognizer are dependencies, right? Would it make sense to put them there?

Would make it easier to fetch/update everything you need via npm.

**Comment by sandstrom** [comment]
I'm doing some issues-gardening 🍀 🌷  and stumbled upon this. Is this still an issue? if not, perhaps it can be closed?

**Comment by ghost23** [comment]
Hi,

nowadays, many developers use npm packages in their browser based apps via webpack or similar tools. In these cases, you need clearly stated dependencies. devDependencies on the other hand usually only define libs or tools you need for building your project. So, yes, I still think, it would make sense to put the mentioned libs as dependencies.

**Comment by nathanhammond** [comment]
Confirm, this should be addressed–I'm just not up-to-date on the consequences upstream for Ember. (Good guy Ember build handles these dependencies for us.)

**Comment by rwjblue** [comment]
Yeah, the bundling is assumed by router.js, and is handled by Ember itself.  I think more appropriately these should be `peerDependencies` with a min version...

**Comment by rmehlinger** [comment]
The behavior of peerDependencies has changed as of NPM3: https://codingwithspike.wordpress.com/2016/01/21/dealing-with-the-deprecation-of-peerdependencies-in-npm-3/

**Comment by rwjblue** [comment]
https://github.com/tildeio/router.js/pull/206 added these packages as peerDependencies
