### ISSUE TITLE
Update ember-cli

### ISSUE THREAD

**Issue by ef4** [tildeio/router.js#140]
Can't `npm install` within the repo, because it tries to load ember-cli 0.0.40, which depends on "expresss".

**Comment by pixelhandler** [comment]
How is ember cli used?

**Comment by stefanpenner** [comment]
@pixelhandler for the build

**Comment by stefanpenner** [comment]
o, it is quite an old one too: https://github.com/tildeio/router.js/blob/master/package.json#L26 0.0.41 or something

**Comment by pixelhandler** [comment]
@stefanpenner in the Gruntfile it appears to just use Broccoli.

- https://github.com/tildeio/router.js/blob/master/Gruntfile.js#L19-L21
