### ISSUE TITLE
Provide `transition` argument for setupContexts while in an intermediate transition.

### ISSUE THREAD

**Issue by rwjblue** [tildeio/router.js#143]
`setupContexts` accepts a transition object as its third argument, but we are not passing one for intermediate transitions (see [here](https://github.com/tildeio/router.js/blob/a1ffd97dc66a6d9d4e8dd89a72c1c4e21a3328c5/lib/router/router.js#L40)).

Changing that so that `newTransition` is defined prior to calling `setupContexts` and just passing it in, does seem to work (at least the transition is not undefined in `Ember.Route#resetController`), but I am not certain if that is the correct fix here.

@machty - What should the `transition` object be for an intermediate transition?

**Comment by vluoto** [comment]
I wonder whether you guys came into some conclusion regarding this issue? I've bumped into this in a situation where I'll most of the time want to clear a certain query parameter when exiting the route with the exception of one particular route.

To give some context: when a user searches for an issue in issue listing, `search_term` query parameter gets set. Now if the user finds their issue, they'll navigate to that particular issue. After they're done with checking the issue, they'll navigate back to issue listing and will expect to see the state where they left it (`search_term` being present). Now that I don't seem to have access to `transition` in `resetController` of my route, I can't check where we are heading next, so `search_term` will always get cleared.

Do let me know if I'm completely off track here and should be looking elsewhere. Cheers!

**Comment by sly7-7** [comment]
@rwjblue It seems like this issue can be closed since the recent work done by @rreckonerr

**Comment by rwjblue** [comment]
Thank you!
