### ISSUE TITLE
unexisting ''redirect" and "contextDidChange" hook

### ISSUE THREAD

**Issue by Peng-Peng** [tildeio/router.js#150]
I try to use this lib standalone and even the simplest sample does not work. Looks like router.js tries to call a "redirect" handler after "afterModel".  

Tracing the commit history reveals that commit a666c9 removed the condition check before calling hooks and in the callHook function it does not check for existence of obj[hookName] before invoking it.

**Comment by machty** [comment]
Ouch, I'm surprised our tests are not catching this if this is happening; any chance you could provide a breaking test case? If not, that's fine, but it would help speed things along

**Comment by Peng-Peng** [comment]
Please open this proto http://jsfiddle.net/qLyq6ppo/9/ in Firefox,  as
Chrome has problem loading external scripts.



2015-02-25 22:16 GMT+08:00 Alex Matchneer <notifications@github.com>:

**Comment by rwjblue** [comment]
Seems like this is working properly now, see here: https://github.com/tildeio/router.js/blob/f3ff6564cb817b2cdb620ab430964f19e67c4919/lib/router/utils.js#L211-L221
