### ISSUE TITLE
Unable to initialize Router

### ISSUE THREAD

**Issue by iamrichardng** [tildeio/router.js#152]
Hi,

I have tried creating a new router as follow:

`var router = new Router();`

But this is what I get:

![image](https://cloud.githubusercontent.com/assets/8440496/6611457/482f12e8-c8a7-11e4-9e66-8b6cd7f395e5.png)

The order of the script import is as follow:

`<script src="lib/routerjs/rsvp-latest.js"></script>`
`<script src="lib/routerjs/route-recognizer.js"></script>`
`<script src="lib/routerjs/router-latest-s3.js"></script>`
`<script src="scripts/routing.js"></script>` --> this contains the initialization of the `new Router()`

The library I am using is downloaded from S3 hosting with the following link:
`http://routerjs.builds.emberjs.com.s3.amazonaws.com/router-latest.js`

Could you please advise?

**Comment by schramile** [comment]
Hi,

Anyone from the team could advise?

Thank you.

**Comment by ahaurw01** [comment]
@schramile See issue #100. When you are not within an ES6 world, you need to manually access the `.default` property of the module.

```javascript
var router = new Router.default();
```
