### ISSUE TITLE
Asynchronous loading of route handlers - missing use case

### ISSUE THREAD

**Issue by jmlamare** [tildeio/router.js#154]
This is a improvement idea dedicated to split large web applications into sub-modules (with asynchronous loaders like requirejs for instance).

Currently, the call to "getHandler" is expected to return the route handler synchronously.
Developpers are required to mock the full handler interface if they wants to asynchronously load a javascript module dedicated to the route processing.

Best Regards

**Comment by stefanpenner** [comment]
yes, this is absolutely something we want/need/intend to do (or receive help from a contributor)

**Comment by trentmwillis** [comment]
This can be closed now via #183.
