### ISSUE TITLE
Provide typescript definition files.

### ISSUE THREAD

**Issue by nmabhinandan** [tildeio/router.js#157]

**Comment by nathanhammond** [comment]
If somebody wishes to do this we're not opposed but it's a low-priority task for those of us maintaining the library. We'll be glad to help somebody through the process, however!

Please stop by [#dev-router](https://embercommunity.slack.com/messages/dev-router/) in the [Ember Community Slack](https://ember-community-slackin.herokuapp.com/) if you want to help us do this!
