### ISSUE TITLE
resolvedModels being set incorrectly for nested routes?

### ISSUE THREAD

**Issue by barelyknown** [tildeio/router.js#159]
I'm very unfamiliar with the inner workings of the router, but I think that I ran across a bug where the `resolvedModels` was being set incorrectly for a parent route.

``` js
// router.js
this.resource('organization', { path: '/organizations/:organization_id' }, function() {
  this.resource('organization.buyer', { path: '/buyer' }, function() {
    // ...   
  }
}
```

If I use the `modelFor('organization')` function here, sometimes the `model` for the `buyer` controller is returned instead of the `model` for the `organization` controller. I found my way to the `resolvedModels` and saw that it was set incorrectly there.

``` js
// app/routes/organization/buyer.js v1
export default Ember.Route.extend({
  model: function() {
    return this.modelFor('organization').get('buyer');
  }
});
```

If I change the nested route to look up the parent `model` from the `store` using the `params` of the parent route, everything works as expected.

``` js
// app/routes/organization/buyer.js v2
export default Ember.Route.extend({
  model: function(params, transition) {
    return this.store.find('organization', transition.params.organization.organization_id).then(function(organization) {
      return organization.get('buyer');
    });
  }
});
```

Is this a bug in the router, or something else that I'm not understanding or doing correctly?

**Comment by Serabe** [comment]
@barelyknown is this still happening?

**Comment by nathanhammond** [comment]
The behavior described here seems like it would break a tremendous number of applications. Given that this has been ignored for over 1.5 years I'm going to operate on the assumption that if it were a router.js problem we'd have multiple reports by this time.

I'm closing this for reason of "probably works." I feel like this is a reasonable assumption to make given the situation. @barelyknown if you can create a reproduction of this behavior in a new Ember CLI application using the most recent version of Ember we'll be glad to revisit and investigate!

(Sorry to have left this hanging for so long!)
