### ISSUE TITLE
Prefixed dynamic segments

### ISSUE THREAD

**Issue by buschtoens** [tildeio/router.js#173]
Originally reported here: emberjs/ember.js#12640

Currently it is not possible to have URLs with "prefixed" dynamic segments. At least I don't know how to do it.

``` js
Router.map(function() {
  this.route('user', {
    path: '/@:user_handle'
  });
});
```

I'd expect Ember to load the `user` route when I enter a URL like `/@buschtoens`. Just like Medium does: [`medium.com/@buschtoens`](https://medium.com/@buschtoens)

Am I doing something wrong or does this really not work? Is there an alternative to achieve this behavior?

The first thing I could think of is a catch-all route that redirects unhandled`/@something` routes to `/user/something`. I'd really like to keep the `@` URL structure though.

**Comment by jmeas** [comment]
One way to support this without big changes to the underlying algorithms here would be [regexp for dynamic segments](https://github.com/jmeas/router-comparison#regex-for-dynamic).

Atm you just have to use a regular old dynamic segment and do the check for `@` yourself. 

Btw this should probably go in the [route-recognizer](https://github.com/tildeio/route-recognizer/blob/bc309e6f8aa43872db943f6445debdd0614188ee/lib/route-recognizer.js#L54) repo.

Another way to support it would be completely rewriting route-recognizer to use a system more like what Backbone uses, where it creates one long regex per route by parsing each character in the string, but I think that's a less elegant algorithm.

**Comment by buschtoens** [comment]
Thanks for replying!

Currently I do this:

```js
Router.map(function() {
  this.route('user', {
    path: '/user/:user_handle'
  });

  this.route('catchAll', {
    path: '/*wildcard'
  });
});
```

```js
// app/catch-all/route.js
import Ember from 'ember';

export default Ember.Route.extend({
  model(params) {
    if (params.wildcard[0] === '@') {
      this.transitionTo('user', params.wildcard.substr(1));
    } else {
      // 404 stuff
    }
  }
});
```
But this kinda removes the whole sense, as I want users to be able to copy the URL from the address bar. So I'd have to have the `catchAll` route actually handle / be the `user` route, like you suggested.

This doesn't feel right. And would get extremely ugly, if I were to add similar prefixed dynamic segments.

I really like the RegExp approach you linked. That would allow for more flexibility.

**Comment by t4t5** [comment]
Has anyone found a way to achieve this?

**Comment by jmeas** [comment]
@t4t5 seems like @buschtoens 's approach is still the best way to do this. Is that not working for you?

**Comment by t4t5** [comment]
@buschtoens's solution is a little so-so. As he pointed out, the URL can't be copied since the user is essentially just redirected. 

It turns out the desired result is actually not too hard to achieve with `path: '/:user_handle'` though, as you mentioned earlier! 

I did this:

```javascript
// app/router.js
this.route('user', { path: '/:userHandle' });
```

```javascript
// app/user/route.js
export default Ember.Route.extend({
  model: function(params) {
    let userHandle = params.userHandle;

    if (!userHandle || userHandle[0] !== "@") {
      return this.transitionTo('fourOhFour');
    }
    
    // Get everything after "@"
    let username = userHandle.substring(1);

    return this.store.queryRecord('user', { 
      username: username 
    });
  }
});
```

I then added a computed property on the user's model, for the `link-to` tags:

```javascript
// app/models/user.js
userHandle: Ember.computed('username', function() {
  return '@' + this.get('username');
})
```

And now you can just use `{{#link-to "user" user.userHandle}}` when linking to a user!

Thanks for the help!

**Comment by buschtoens** [comment]
@t4t5 Oh, that's neat! Thanks for sharing. :smile:

**Comment by rwjblue** [comment]
Seems like https://github.com/tildeio/router.js/issues/173#issuecomment-227652485 is a good solution here, closing...
