### ISSUE TITLE
Handling 404s or not found / missing routes?

### ISSUE THREAD

**Issue by robdodson** [tildeio/router.js#176]
I've tried looking over the docs and issue tracker but haven't quite found an answer for this yet...

I'm trying to use a wildcard symbol to create a 404 route:

```
router.map(function(match) {
  match('*').to('notFound');
});
```

But this doesn't seem to ever run. I'm able to get other routes to match just fine so I feel like I'm missing something really obvious. Much thanks to anyone who has time to look into this :cake:

**Comment by jmeas** [comment]
Did you look through the tests for this use case? I'm on mobile github or I'd provide more direction

**Comment by robdodson** [comment]
Thanks @jmeas good call. I just looked through and found [this one](https://github.com/tildeio/router.js/blob/master/test/tests/router_test.js#L88) which seems to fit the bill. Here's my updated code:

```
router.handleURL(url)
  .catch(function(err) {
    if (err.name == 'UnrecognizedURLError') {
      // do 404 stuff here
    }
  });
```

This works, just curious if this is the intended way to do this?

**Comment by jmeas** [comment]
Still on mobile, but I remember that embers API wraps this one with some sugar. so that _could_ be the intended way to do it when using this library directly. I can investigate further later.

**Comment by jmeas** [comment]
The issue may be that you need to name the splat, `*notFound` rather than just *

**Comment by robdodson** [comment]
Ah yeah that did it :)

```
this.router.map(function(match) {
  match('*notfound').to('notFound');
});
```

Matches now.

**Comment by jmeas** [comment]
Oh, and you may already know this, but the DSL in this library comes from [route-recognizer](https://github.com/tildeio/route-recognizer). It is, for instance, where the requirement that every splat and dynamic segment be named comes from. Checking out that library could be useful while learning this one.

**Comment by robdodson** [comment]
Thanks @jmeas! yeah I've been sort of jumping back and forth between route-recognizer and this repo to piece together my understanding of things :)
