### ISSUE TITLE
Router does not recognize poorly encoded dynamic segments

### ISSUE THREAD

**Issue by seanjohnson08** [tildeio/router.js#178]
In the app that I am currently maintaining, we have some external URLs that are coming in that are improperly escaped. These URLs have been out in the wild now for over 5 years, and there's not a whole lot we can do to change them.

Normally I could work around this, or handle it on my side - but the router does not give me the means to do so. The router ends up actually throwing a JS Error (`URI Malformed`) and the entire app grinds to a halt then and there.

Here's an example of a poorly encoded URL: `/compose-message/Parab%E9ns%20pelo%20seu%20novo%20cargol`

The key takeaway is that "%E9" - that is the result of calling `escape('é')`. I know that the router is doing the right thing by using the `URI` family of functions (they are UTF compliant) but would it be at all possible to either handle these poorly escaped URLs or give me some kind of hook into which I can handle them myself?

I've written a test case that currently fails for this here: https://github.com/seanjohnson08/router.js/commit/a92c748947556653bd8df39460ffe948e61307fe

Thank you for any guidance.

**Comment by mmun** [comment]
This sounds like a good idea.

**Comment by krisselden** [comment]
route recognizer should unescape segments after split('/'), this issue should be opened on route-recognizer

**Comment by krisselden** [comment]
please reopen on https://github.com/tildeio/route-recognizer
