### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by oskarrough** [tildeio/router.js#179]
Hi, is usage of router.js outside of Ember not recommended? I couldn't find the package on npm and the builds page from the documentation seems out of date: http://routerjs.builds.emberjs.com.s3-website-us-east-1.amazonaws.com/index.html.

Just looking for advice, thank you.

**Comment by jmeas** [comment]
Related: #69 and #70

Publishing to npm has been a 2 yr endeavor lol 😛

**Comment by nathanhammond** [comment]
We're publishing to npm as of 1.2.4: https://www.npmjs.com/package/router_js

**Comment by kojilab** [comment]
I used the npm in my brunch project and when I use require('router_js') it doesn't work. 

Error is 

router.js:1666 Uncaught TypeError: Cannot read property 'Promise' of undefined(…)
