### ISSUE TITLE
#187 seems to crash PhantomJS 1.9 with a syntax error

### ISSUE THREAD

**Issue by simonihmig** [tildeio/router.js#188]
I noticed with a PR on one of my addons (https://github.com/kaliber5/ember-bootstrap/pull/123) that builds in TravisCI with ember canary were suddenly broken. They were actually not failing (which would be acceptable), but they seem to crash the whole build, TravisCI says: 

> No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
>
> The build has been terminated

When running `ember try:each`, the canary build shows this:

```
not ok 1 PhantomJS 1.9 - Global error: SyntaxError: Parse error at http://localhost:7357/assets/vendor.js, line 75982
    ---
        Log: |
            { type: 'error',
              text: 'SyntaxError: Parse error at http://localhost:7357/assets/vendor.js, line 75982\n' }
    ...
not ok 2 PhantomJS 1.9 - Global error: Error: Could not find module ember-metal/core required by: ember-testing/index at http://localhost:7357/assets/test-support.js, line 62
    ---
        Log: |
            { type: 'error',
              text: 'Error: Could not find module ember-metal/core required by: ember-testing/index at http://localhost:7357/assets/test-support.js, line 62\n' }
    ...
not ok 3 PhantomJS 1.9 - Global error: ReferenceError: Can't find variable: define at http://localhost:7357/assets/dummy.js, line 24
    ---
        Log: |
            { type: 'error',
              text: 'ReferenceError: Can\'t find variable: define at http://localhost:7357/assets/dummy.js, line 24\n' }
    ...
not ok 4 PhantomJS 1.9 - Global error: ReferenceError: Can't find variable: define at http://localhost:7357/assets/tests.js, line 24
    ---
        Log: |
            { type: 'error',
              text: 'ReferenceError: Can\'t find variable: define at http://localhost:7357/assets/tests.js, line 24\n' }
    ...
not ok 5 PhantomJS 1.9 - Global error: ReferenceError: Can't find variable: EmberENV at http://localhost:7357/1738/tests/index.html?hidepassed, line 39
    ---
        Log: |
            { type: 'error',
              text: 'ReferenceError: Can\'t find variable: EmberENV at http://localhost:7357/1738/tests/index.html?hidepassed, line 39\n' }
    ...
``` 
Here the Travis logs from two addons, the latter with no code change for several weeks:
* https://travis-ci.org/kaliber5/ember-bootstrap/builds/151867897
* https://travis-ci.org/kaliber5/ember-bootstrap-changeset-validations/builds/139417638

The offending line is this one, coming from #187 : https://github.com/tildeio/router.js/blob/b921fd3407064a77bd99f4f4eddc4377592ac93b/lib/router/handler-info.js#L67

After upgrading the one addon that was affected by this to ember-cli 2.7.0, which includes the TravisCI setup for PhantomJS 2.x, this issue was resolved. 

I am aware that PhantomJS 1.9 is known to crash easily. However as there are probably a whole lot of addons out there, that are still configured to run with 1.9 and have a canary test run through their default ember-try config, I think this is an issue. Again, this is not about a failing canary test run, but a crashing build!

Hope this helps...

**Comment by rwjblue** [comment]
Ya, we will need to fix. Thank you for reporting!
