### ISSUE TITLE
Move To ES6/Rollup

### ISSUE THREAD

**Issue by chadhietala** [tildeio/router.js#208]
Having to do some weird stuff to get this to work in Ember.

https://github.com/emberjs/ember.js/pull/15037/files#diff-ba838c016eaa3f8c07cd4a585163371eR16

**Comment by rtablada** [comment]
@chadhietala this will also touch route-recognizer.

I'm ready to help since this is also a blocker for me writing docs on router.js and libs like preact and/or Glimmer.

Is there a lib using Rollup you can point me to that might give some guidance to making a UMD for these packages?

**Comment by chadhietala** [comment]
You can set `route-recognizer` as external and it will be resolved at runtime.

**Comment by rtablada** [comment]
For using it right now, an external works (though documenting that would be helpful).

But for common usecase it will be seen as a -1 for people wanting to `import Router from 'router_js'` and have things "Just Work ™️"

**Comment by foxdonut** [comment]
Indeed it's very disappointing not to be able to use `import Router from 'router_js'`. Are there any plans to address this?

**Comment by locks** [comment]
@foxdonut yes, this issue :P
