### ISSUE TITLE
Which version support IE8?

### ISSUE THREAD

**Issue by guofengzh** [tildeio/router.js#212]
I am sorry that if this is the place to ask a question.

There is call Object.defineProperty(), which does not work on IE8.
Is there any version support IE8? (versions for router,js, route-recognizer and rsvp), or is there any work around for it?

BTW, where can I ask questions for router,js?

Thanks very much!

**Comment by rwjblue** [comment]
Not sure what exact version supports IE8 specifically.  I would double check what version of router.js, route-recognizer, and rsvp that  Ember 1.13 used (it was the last version to support IE8) and go from there.
