### ISSUE TITLE
Type Error while importing as module

### ISSUE THREAD

**Issue by marcalexiei** [tildeio/router.js#221]
Hi, 
While importing router.js via module using _require_ or _import_ I get an error:

`Uncaught TypeError: Cannot read property 'Promise' of undefined(…)`

The same issue has been mentioned in [#179](https://github.com/tildeio/router.js/issues/179#issuecomment-267760579).

**Comment by rwjblue** [comment]
This is essentially a  duplicate of https://github.com/tildeio/router.js/issues/137.
