### ISSUE TITLE
Remove the need for `HandlerInfo.prototype.context = null`

### ISSUE THREAD

**Issue by rwjblue** [tildeio/router.js#225]
We require that `context` be set on on `HandlerInfo.prototype` to null because the checks in `NamedTransitionIntent.prototype.applyToHandlers` [here](https://github.com/tildeio/router.js/blob/v1.2.8/lib/router/transition-intent/named-transition-intent.js#L76-L81) check of `oldHandlerInfo.context === newHandlerInfo.context` and assumes
that the params _must_ match also in that case.

The only reason `oldHandlerInfo.context` and `newHandlerInfo.context` did not match in prior versions is because if the context isn't set yet (on newHandlerInfo) is because it inherits the `null` from the prototype vs `undefined` (on the oldHandlerInfo).

A future refactoring should remove that conditional, and fix the hand full of failing tests.

**Comment by btecu** [comment]
This was solved in https://github.com/tildeio/router.js/pull/242.

**Comment by rwjblue** [comment]
Awesome, thank you for pointing that out!
