### ISSUE TITLE
Error when importing as module

### ISSUE THREAD

**Issue by zacksiri** [tildeio/router.js#238]
I'm getting the following error when i'm using import.

```
import Router from 'router_js'
```

``` js
TypeError: __dependency2__ is undefined
```

I have `route-recognizer` and `rsvp` installed as dependencies.

**Comment by zacksiri** [comment]
here is the output from chrome 

``` js
Uncaught TypeError: Cannot read property 'Promise' of undefined
```

**Comment by locks** [comment]
Hi @zacksiri, is this still relevant? Thanks!

**Comment by zacksiri** [comment]
I have not tried it since. so might no longer be relevant. Feel fee to close it if it's already been resolved.

**Comment by ksinghj** [comment]
@locks working Sep 2020

**Comment by locks** [comment]
Appreciate the update @ksinghj !
