### ISSUE TITLE
Accessing the parent handler in model method (whilst transitioning)

### ISSUE THREAD

**Issue by KidkArolis** [tildeio/router.js#26]
When my handler's model is called, I need to lookup the parent handler's context. I know you guys probably don't need to do that in Ember, but I was wondering if there was a way right now, without changing the code.

I saw the following function being used in Ember
```
function parentRoute(route) {
  var handlerInfos = route.router.router.targetHandlerInfos;

  if (!handlerInfos) { return; }

  var parent, current;

  for (var i=0, l=handlerInfos.length; i<l; i++) {
    current = handlerInfos[i].handler;
    if (current === route) { return parent; }
    parent = current;
  }
}
```
But that will only work in activate or setup, where the router.targetHandlerInfos has already been set. Can this be achieved from `model`?

**Comment by jmeas** [comment]
@KidkArolis is this still an issue for you? (rofl 2 years later)

**Comment by KidkArolis** [comment]
Nah, I moved on from router.js (... https://medium.com/@kidkarolis/sunday-coffeeshop-and-cherrytree-448614b5a02d)
