### ISSUE TITLE
Multiple params in a single route path

### ISSUE THREAD

**Issue by KidkArolis** [tildeio/router.js#60]
I've noticed this doesn't work:

```
router.generate("foo", 1, 2);
```

if both of those params belong to the same route.

```
this.route("foo", {path: "/:param1/:param2"});
```

due to how only a single name is passed to `getMatchPointObject` (https://github.com/tildeio/router.js/blob/master/lib/router.js#L480).

Is this by design (e.g. related to models), or is this something that should/could be fixed?

**Comment by jmeas** [comment]
Is this still an issue...?

**Comment by stefanpenner** [comment]
@jmeas if you have time, adding a quick test to the test suite may both reveal if this issue is valid and provide another piece of coverage.

**Comment by nathanhammond** [comment]
The tests from #164 proved that this is not an issue. Closing, will still attempt to land the PR.
