### ISSUE TITLE
Use a different Promise implementation

### ISSUE THREAD

**Issue by pateketrueke** [tildeio/router.js#82]
Just say, the RSVP dependency can be replaced by another, i.e Q.

What do you think?

**Comment by jmeas** [comment]
Bluebird is probably a bit much, I think.

If there aren't any non-spec features being used here, then I suggest that the lib **assume** that the user has an A+ promise available globally.

```js
if (typeof Promise !== 'undefined') {
  Router.Promise = Promise;
}
```

Then, in legacy environments, the user can specify any promise lib they want.

##### Pros

- Works in modern browsers w.o. any promise polyfills/extensions
- User can use whatever library they want (even bluebird!)

##### Cons

- Marginally more difficult to set up in legacy environments

**Comment by nathanhammond** [comment]
The Ember community has standardized on RSVP and as such we don't intend to make this pluggable. As the time comes to migrate to native implementations nears we may revisit this.
